---
- name: Collect various show commands on device
  hosts: nx01
  connection: network_cli
  gather_facts: false

  vars:
    output_dir: out
    commands:
      - show version
      - show interface status up

  tasks:

  - name: Ensure {{ output_dir }} exists
    file:
      path: "{{ output_dir }}"
      state: directory
      mode: '0755'
    run_once: true

  - include_tasks:
      file: nxos-command.yml
    loop: "{{ commands }}"
