---
all:
  vars:
    ansible_user: admin
    ansible_password: demo
    snmp_location: Undefined
  hosts:
    nx01:
      ansible_network_os: nxos
    rt01:
      ansible_network_os: ios
    xr01:
      ansible_network_os: iosxr
routers:
  vars:
    foo: routers
  hosts:
    rt01:
    xr01:
switches:
  hosts:
    nx01:
...
